export const data = [
    { 
        firstname: 'Jane', 
        lastname: 'Doe', 
        startDate: '11/10/2019',
        department: 'Sales',
        dateBirth:'04.09.2001',
        street: 'Mapple Street, 12',
        city: 'New York',
        state: 'New York',
        zipCode: '10006',
    },
    { 
        firstname: 'Mohamed', 
        lastname: 'Ali', 
        startDate: '11/10/2012',
        department: 'Human Ressources',
        dateBirth:'01/17/1942',
        street: 'Boxer Street, 256',
        city: 'Louisville',
        state: 'Kentucky',
        zipCode: '40475',
    },
    { 
        firstname: 'Diane', 
        lastname: 'Fossey', 
        startDate: '07/23/2010',
        department: 'ingineering',
        dateBirth:'12/26/1985',
        street: 'Gorilla Avenue, 1932',
        city: 'San Fransisco',
        state: 'California',
        zipCode: '94016',
    },
    { 
        firstname: 'Ray', 
        lastname: 'Charles', 
        startDate: '08/04/2006',
        department: 'Marketing',
        dateBirth:'09/23/1970',
        street: 'Road Jack, 1962',
        city: 'Albany',
        state: 'Georgia',
        zipCode: '31701',
    },
    { 
        firstname: 'Grace', 
        lastname: 'Hopper', 
        startDate: '10/17/2002',
        department: 'Legal',
        dateBirth:'12/09/1967',
        street: 'Amazing Grace Street, 1906',
        city: 'New York',
        state: 'New York',
        zipCode: '10001',
    },
]